name: Cloudbase-Init build MSI

on: [push, pull_request]

jobs:
  build:

    runs-on: windows-2019
    strategy:
      max-parallel: 100
      matrix:
        cbsinit_repo: ['https://github.com/crislub/cloudbase-init-1']
        cbsinit_branch: ['feature-remove-mac']
        cbsinit_name: ['conf-network']

    steps:
    - uses: actions/checkout@v1
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1
    - name: Install Windows 8.1 SDK
      run: |
        Invoke-WebRequest -Method Get -Uri https://go.microsoft.com/fwlink/p/?LinkId=323507 -OutFile sdksetup.exe -UseBasicParsing
        Start-Process -Wait sdksetup.exe -ArgumentList "/q", "/norestart", "/features", "OptionId.WindowsDesktopSoftwareDevelopmentKit", "OptionId.NetFxSoftwareDevelopmentKit"
      shell: powershell
    - name: Build msi
      shell: cmd
      run: 
        powershell.exe .\BuildAutomation\BuildCloudbaseInitSetup.ps1^
            -ClonePullInstallerRepo:$false -CreateZip:$false ^ 
            -SetVCEnvVars:$true -RelativePythonDirPath:$true ^
            -CloudbaseInitRepoUrl ${{ matrix.cbsinit_repo }} -CloudbaseInitRepoBranch ${{ matrix.cbsinit_branch }}
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.run_number }}
        release_name: Release ${{ github.run_number }}
        draft: false
        prerelease: false
    - name: upload msi artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: 'CloudbaseInitSetup/bin/release/x64/CloudbaseInitSetup.msi'
        asset_name: "CloudbaseInit_x64_MSI_${{ matrix.cbsinit_name }}"
        asset_content_type: application/msi

